name: Go Formatting

on:
  push:
    branches:
      - main

jobs:
  gofmt:
    name: Apply and commit formatting
    runs-on: ubuntu-latest
    # Only run on 'push' events to the 'main' branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Set permissions for the job to allow pushing changes back to the repo
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        # Use a token with 'contents: write' scope for pushing changes
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default token with push rights

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Apply gofmt
        # This command applies formatting changes to files
        run: gofmt -w .

      - name: Check for changes
        id: git-check
        # Check if gofmt actually modified any files
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        shell: bash

      - name: Commit and push changes
        # Only run this step if changes were detected
        if: steps.git-check.outputs.no_changes == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto-apply gofmt formatting 🤖"
          git push